export const CLEAR_IMAGE_SRCS = 'CLEAR_IMAGE_SRCS';
export const RESET_LOADED_IMAGE_COUNT = 'RESET_LOADED_IMAGE_COUNT';


export const SET_IMAGE_SRCS = 'SET_IMAGE_SRCS';
export const SET_TRACK = 'SET_TRACK';

export const INCREMENT_LOADED_IMAGES = 'INCREMENT_LOADED_IMAGES';