export const CLEAR_IMAGE_SRCS = 'CLEAR_IMAGE_SRCS';
export const RESET_LOADED_IMAGE_COUNT = 'RESET_LOADED_IMAGE_COUNT';


export const SET_IMAGE_SRCS = 'SET_IMAGE_SRCS';
export const SET_TRACKS = 'SET_TRACKS';

export const ADD_AUDIO_BUFFER = 'ADD_AUDIO_BUFFER';
export const INCREMENT_LOADED_BUFFER_COUNT = 'INCREMENT_LOADED_BUFFER_COUNT';
export const INCREMENT_LOADED_IMAGES = 'INCREMENT_LOADED_IMAGES';
export const INCREMENT_ANALYSED_TRACK_COUNT = 'INCREMENT_ANALYSED_TRACK_COUNT';