export const REQUEST_TAG_PHASE   = 'REQUEST_TAG_PHASE';  
export const FIND_ASSETS_PHASE    = 'FIND_ASSETS_PHASE';  
export const LOAD_ASSETS_PHASE    = 'LOAD_ASSETS_PHASE';  
export const PLAY_ANIMATION_PHASE = 'PLAY_ANIMATION_PHASE';

export const LOAD_ASSETS = 'LOAD_ASSETS';